-- MySQL Script generated by MySQL Workbench
-- Thu Aug 31 23:54:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------

-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema tienda_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tienda_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tienda_db` DEFAULT CHARACTER SET utf8 ;
USE `tienda_db` ;

-- -----------------------------------------------------
-- Table `tienda_db`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_db`.`categoria` (
  `id_categoria` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_db`.`recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_db`.`recibo` (
  `id_recibo` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  `serie` VARCHAR(200) NULL DEFAULT NULL,
  `total` DECIMAL(6,2) NULL DEFAULT NULL,
  `deposito` DECIMAL(6,2) NULL,
  `saldo` DECIMAL(6,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_recibo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_db`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_db`.`rol` (
  `id_rol` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_db`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_db`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  `eliminado` TINYINT(4) NULL DEFAULT 0,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `nombre` VARCHAR(50) NULL,
  `apellido` VARCHAR(50) NULL,
  `ci` VARCHAR(10) NULL,
  `direccion` VARCHAR(100) NULL,
  `celular` VARCHAR(45) NULL,
  `id_rol` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `fk_Usuario_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `tienda_db`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_db`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_db`.`reserva` (
  `id_reserva` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  `direccion` VARCHAR(250) NOT NULL,
  `ubicacion` VARCHAR(250) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `fecha_entrega` DATETIME NOT NULL,
  `referencia` VARCHAR(45) NULL DEFAULT NULL,
  `id_usuario` INT(11) NOT NULL,
  PRIMARY KEY (`id_reserva`),
  CONSTRAINT `fk_reserva_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tienda_db`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_db`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_db`.`producto` (
  `id_producto` INT(11) NOT NULL AUTO_INCREMENT,
  `fecha_creacion` DATETIME NULL DEFAULT NULL,
  `fecha_actualizacion` DATETIME NULL DEFAULT NULL,
  `eliminado` TINYINT(4) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` VARCHAR(250) NULL DEFAULT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  `id_categoria` INT(11) NOT NULL,
  PRIMARY KEY (`id_producto`),
  CONSTRAINT `fk_Producto_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tienda_db`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `tienda_db`.`detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tienda_db`.`detalle` (
  `id_producto` INT(11) NOT NULL,
  `id_reserva` INT(11) NOT NULL,
  `cantidad` INT NULL,
  `sub_total` DECIMAL(6,2) NULL,
  `precio_total` DECIMAL(6,2) NULL,
  `id_recibo` INT(11) NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_actualizacion` DATETIME NULL,
  `eliminado` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id_producto`, `id_reserva`, `id_recibo`),
  CONSTRAINT `fk_producto_has_reserva_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tienda_db`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_has_reserva_reserva1`
    FOREIGN KEY (`id_reserva`)
    REFERENCES `tienda_db`.`reserva` (`id_reserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_recibo1`
    FOREIGN KEY (`id_recibo`)
    REFERENCES `tienda_db`.`recibo` (`id_recibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
